version: '3.1'
services:
  web:
    container_name : odoo
    image: odoo:latest
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
    - POSTGRES_PASSWORD=tes
    - POSTGRES_USER=tes
    - DB_PORT_5432_TCP_ADDR=localhost
    - DB_PORT_5432_TCP_PORT=5432
volumes:
  odoo-web-data:
