version: '3.1'
services:
  web:
    container_name : odoo
    image: odoo:latest
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
    - HOST=localhost
    - USER=tes
    - PASSWORD=tes
volumes:
  odoo-web-data:
